version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}
services:
  postgres:
    container_name: postgres_server
    build: ./docker_compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env_prod
    deploy:
      restart_policy:
        condition: on-failure
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: ./docker_compose/django/production/Dockerfile
    user: django
    command: /start.sh
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env_prod
  nginx:
    container_name: nginx_server
    build: ./docker_compose/nginx
    depends_on:
      - django 
    ports:
      - "80:80"
      - "443:443"
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:3.0
    deploy:
      restart_policy:
        condition: on-failure
